MvcWebUI/Models/ErrorViewModel.cs
namespace MvcWebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcWebUI/Areas/Account/Controllers/UsersController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace MvcWebUI.Areas.Account.Controllers
{
    [Area("Account")] // route üzerinden area adı
    public class UsersController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ICountryService _countryService;
        private readonly ICityService _cityService;

        public UsersController(IAccountService accountService, ICountryService countryService, ICityService cityService)
        {
            _accountService = accountService;
            _countryService = countryService;
            _cityService = cityService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(AccountLoginModel model)
        {
            if (ModelState.IsValid)
            {
                var userResult = new UserModel();
                var result = _accountService.Login(model, userResult);
                if (result.IsSuccessful)
                {
                    List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, userResult.UserName),
                        new Claim(ClaimTypes.Role, userResult.RoleNameDisplay),
                        new Claim(ClaimTypes.Sid, userResult.Id.ToString())
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
                ModelState.AddModelError("", result.Message);
            }
            return View();
        }

        public IActionResult Register()
        {
            ViewBag.Countries = new SelectList(_countryService.Query().ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(AccountRegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _accountService.Register(model);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Login));
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.Countries = new SelectList(_countryService.Query().ToList(), "Id", "Name", model.UserDetail.CountryId);
            ViewBag.Cities = new SelectList(_cityService.GetList(model.UserDetail.CountryId ?? 0), "Id", "Name", model.UserDetail.CityId);
            return View(model);
        }

        public IActionResult AccessDenied()
        {
            return View("_Error", "You don't have access to this operation!");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home", new { area = "" });
        }
    }
}

MvcWebUI/Controllers/CartController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace MvcWebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductService _productService;

        public CartController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult AddToCart(int productId)
        {
            List<CartItemModel> cart = GetFromSession();



            ProductModel product = _productService.Query().SingleOrDefault(p => p.Id == productId);
            if (product is null)
                return View("_Error", "Product not found!");
            if (product.StockAmount == 0)
            {
                TempData["Message"] = "The product added to cart is not available in stock!";
                return RedirectToAction("Index", "Products");
            }
            int userId = Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value);
            CartItemModel cartItem = new CartItemModel()
            {
                ProductId= productId,
                ProductName = product.Name,
                UnitPrice = product.UnitPrice ?? 0,
                UserId = userId
            };
            cart.Add(cartItem);
            // sepetteki eklenen ÜRÜN sayısı
            int cartProductCount = cart.Count(c => c.ProductId == productId);
            if (cartProductCount > product.StockAmount)
            {
                TempData["Message"] = "The product added to cart is not available in stock!";
            }
            else
            {
                string cartJson = JsonConvert.SerializeObject(cart); // C# -> JSON: Serialize
                HttpContext.Session.SetString("cart", cartJson);
                TempData["Message"] = product.Name + " " + " with " + cartProductCount + " amount added to cart.";
            }
            return RedirectToAction("Index", "Products");
        }

        private List<CartItemModel> GetFromSession()
        {
            List<CartItemModel> cart = new List<CartItemModel>();
            string? cartJson = HttpContext.Session.GetString("cart");
            if (!string.IsNullOrWhiteSpace(cartJson))
                cart = JsonConvert.DeserializeObject<List<CartItemModel>>(cartJson); // JSON -> C#: Deserialize
            return cart;
        }

        public IActionResult GetCart()
        {
            List<CartItemModel> cart = GetFromSession();
            var groupByCart = from c in cart
                              group c by new { c.ProductId, c.UserId, c.ProductName }
                              into cGroupBy
                              select new CartItemGroupByModel()
                              {
                                  ProductId = cGroupBy.Key.ProductId, // gruplananlar key ile ulaşılır
                                  UserId = cGroupBy.Key.UserId,
                                  ProductName = cGroupBy.Key.ProductName,
                                  TotalUnitPrice = cGroupBy.Sum(cgb => cgb.UnitPrice),
                                  TotalUnitPriceDisplay = cGroupBy.Sum(cgb => cgb.UnitPrice).ToString("C2"),
                                  TotalCount = cGroupBy.Count()
                              };

            groupByCart = groupByCart.OrderBy(gbc => gbc.ProductName).ToList();

            //return View("Cart", cart);
            return View("GroupByCart", groupByCart);
        }

        public IActionResult Delete(int productId, int userId)
        {
            List<CartItemModel> cart = GetFromSession();
            CartItemModel cartItem = cart.FirstOrDefault(c => c.ProductId == productId && c.UserId == userId);
            if (cartItem is not null)
            {
                cart.Remove(cartItem);
                HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cart));
                TempData["Message"] = "Product removed from cart.";
            }
            return RedirectToAction(nameof(GetCart));
        }

        public IActionResult ClearCart()
        {
            //HttpContext.Session.Clear();
            //HttpContext.Session.Remove("cart");
            var cart = GetFromSession();
            var userCart = cart.Where(c => c.UserId == Convert.ToInt32(User.Claims.SingleOrDefault(cl => cl.Type == ClaimTypes.Sid).Value)).ToList();
            foreach (var userCartItem in userCart)
            {
                cart.Remove(userCartItem);
            }
            var cartJson = JsonConvert.SerializeObject(cart);
            HttpContext.Session.SetString("cart", cartJson);
            TempData["Message"] = "Cart cleared.";
            return RedirectToAction(nameof(GetCart));
        }
    }
}

MvcWebUI/Controllers/CategoriesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.Entities;
using Business.Services;
using Business.Models;
using Microsoft.AspNetCore.Authorization;

namespace MvcWebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        // Add service injections here
        private readonly ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: Categories
        [AllowAnonymous]
        public IActionResult Index()
        {
            List<CategoryModel> categoryList = _categoryService.Query().ToList(); // TODO: Add get list service logic here
            return View(categoryList);
        }

        // GET: Categories/Details/5
        //[Authorize(Roles = "Admin,User")]
        [Authorize]
        public IActionResult Details(int id)
        {
            CategoryModel category = _categoryService.Query().SingleOrDefault(c => c.Id == id); // TODO: Add get item service logic here
            if (category == null)
            {
                //return NotFound();
                return View("_Error", "Category not found!");
            }
            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryModel category)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add insert service logic here
                var result = _categoryService.Add(category);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(category);
        }

        // GET: Categories/Edit/5
        public IActionResult Edit(int id)
        {
            CategoryModel category = _categoryService.Query().SingleOrDefault(c => c.Id == id); // TODO: Add get item service logic here
            if (category == null)
            {
                //return NotFound();
                return View("_Error", "Category not found!");
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(category);
        }

        // POST: Categories/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryModel category)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add update service logic here
                var result = _categoryService.Update(category);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(category);
        }

        // GET: Categories/Delete/5
        public IActionResult Delete(int id)
        {
            CategoryModel category = _categoryService.Query().SingleOrDefault(c => c.Id == id); // TODO: Add get item service logic here
            if (category == null)
            {
                //return NotFound();
                return View("_Error", "Category not found!");
            }
            return View(category);
        }

        // POST: Categories/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // TODO: Add delete service logic here
            var result = _categoryService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MvcWebUI/Controllers/StoresController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MvcWebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StoresController : Controller
    {
        // Add service injections here
        private readonly IStoreService _storeService;

        public StoresController(IStoreService storeService)
        {
            _storeService = storeService;
        }

        // GET: Stores
        public IActionResult Index()
        {
            List<StoreModel> storeList = _storeService.GetList(); // Add get list service logic here
            return View(storeList);
        }

        // GET: Stores/Details/5
        public IActionResult Details(int id)
        {
            StoreModel store = _storeService.GetItem(id); // Add get item service logic here
            if (store == null)
            {
                return View("_Error", "Store not found!");
            }
            return View(store);
        }

        // GET: Stores/Create
        public IActionResult Create()
        {
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StoreModel store)
        {
            if (ModelState.IsValid)
            {
                // Add insert service logic here
                var result = _storeService.Add(store);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(store);
        }

        // GET: Stores/Edit/5
        public IActionResult Edit(int id)
        {
            StoreModel store = _storeService.GetItem(id); // Add get item service logic here
            if (store == null)
            {
                return View("_Error", "Store not found!");
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(store);
        }

        // POST: Stores/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StoreModel store)
        {
            if (ModelState.IsValid)
            {
                // Add update service logic here
                var result = _storeService.Update(store);
                if (result.IsSuccessful)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", result.Message);
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(store);
        }

        // GET: Stores/Delete/5
        public IActionResult Delete(int id)
        {
            StoreModel store = _storeService.GetItem(id); // Add get item service logic here
            if (store == null)
            {
                return View("_Error", "Store not found!");
            }
            return View(store);
        }

        // POST: Stores/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // TODO: Add delete service logic here
            var result = _storeService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
    }
}

MvcWebUI/Views/Shared/_Error.cshtml
@model string

@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error!</h1>
@if (string.IsNullOrWhiteSpace(Model))
{
    <h2 class="text-danger">An error occurred while processing your request.</h2>
}
else
{
    <h2 class="text-danger">@Model</h2>
}

MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @AppSettings.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcWebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-door"></i> @AppSettings.Title</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Stores" asp-action="Index">Stores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Reports" asp-controller="Home" asp-action="Index">Reports</a>
                            </li>
                        }
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="GetCart">Cart</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <div class="navbar-text">
                        <ul class="navbar-nav me-auto">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-warning" asp-area="Account" asp-controller="Users" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-warning" asp-area="Account" asp-controller="Users" asp-action="Register">Register</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <div class="usernamediv">
                                        <span>@User.Identity.Name</span>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-warning" asp-area="Account" asp-controller="Users" asp-action="Logout">Logout</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; @DateTime.Now.Year - Görkem Baran Şimşek - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>